# Generated by Django 3.1.5 on 2021-01-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20201225_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='user/image/', verbose_name='Image', width_field=100),
        ),
    ]
