# Generated by Django 3.1.5 on 2021-02-11 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_ordered',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_ordered',
            new_name='ordered',
        ),
    ]
