# Generated by Django 3.1.5 on 2021-02-17 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20210210_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0003_auto_20210113_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='hi', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_confirmed',
            field=models.BooleanField(default=True, verbose_name='Confirm'),
        ),
        migrations.AddField(
            model_name='comment',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='Product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.CharField(default=0, max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ShopProduct', related_query_name='ShopProduct', to='Product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='quantity',
            field=models.CharField(default=0, max_length=50, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ShopProduct', related_query_name='ShopProduct', to='Account.shop', verbose_name='Shop'),
        ),
    ]
